#+INCLUDE: frontmatter.org
* Introduction
#+BEGIN_HTML
<img src="https://secure.gravatar.com/avatar/9dcf3befff787a5f1f850fc0990bc9f1?size=400px" width=50%></img>
#+END_HTML
I am a physicist at Duke University studying the production of charm
quarks in hadron collisions at the Large Hadron Collider. You can read
more about my research at my [[http://www.phy.duke.edu/~dmb60/][online lab notebook]]. I am the author of
"[[http://www.phy.duke.edu/~dmb60/the-guide/][The Hitchhiker's Guide to High Energy Physics]]," a resource for making
the transition from the classroom to the sophisticated computing
environment used to perform High Energy Physics experiments. I have
taught recitation sections and labs for the introductory courses in
the Duke Physics department. I have also worked as a private tutor in
physics for the past four years. Below you will find my [[Philosophy of
Teaching]] and my [[Curriculum Vitae]]. Throughout the document you will
find links to additional material which may be of interest.
