#+INCLUDE: frontmatter.org
* Philosophy of Teaching 
As a graduate student in physics, I have had the opportunity to teach
as recitation instructor for "Introduction to Physics for Engineers."
In other semesters I have taught lab sections for this course as well
as "Introduction to Electricity and Magnetism." These experiences, as
well as past instructors have significantly influenced my philosophy
of teaching. I have had two instructors that stand out above all
others in the impact that they have had on the way I approach learning
and solving problems. In reflecting on my approach to teaching I have
realized that these two instructors have also had a significant
influence on how I view instructor-student interactions. When I
approached my high school calculus teacher about taking the course out
of sequence without the prerequisite, his response was to offer
after-hours help and give me the calculus textbook to study over the
summer. He emphasized strategy and efficient execution over rote
memory and brute force. During my freshman year of college, I failed
my first physics midterm miserably. When I met with my professor he
worked with me to develop an extra-curricular study plan, and offered
time outside of office hours to meet and discuss homework problems.
Both of these instructors met me at my level, provided me with extra
resources, and enabled me to succeed.

In order to carry this forward, I believe that it is the
responsibility of any teacher to provide as many resources to enable
learning as possible. This means providing multiple perspectives a
topic, the one presented by the book, my perspective, and the a
perspective supported by mathematics. Office hours provided one-on-one
interactions with students that allow me to refine my explanations of
concepts that can be reincorporated into recitation instruction. As
recitation instructor for "Introduction to Physics for Engineers", I
plan my lessons to complement lectures. Students approach physics from
different levels and backgrounds, and it is important for me to adapt
to the student in order to enable efficient learning. Some students
require individual attention. Sometimes this means explaining a
concept in detail, and sometimes it means discussing test taking
techniques that enable them to succeed. I am available for individual
meetings as well as office hours.

Another aspect of meeting students on their level is the teacher's
responsibility to provide a safe learning environment. This means
making mistakes part of the learning process. This can be achieved in
many different ways. Small groups in office hours allow me to ask one
student to explain to another how a concept works, and also allows
students the opportunity to work in front of me so I can see their
reasoning. Individual meetings can address student anxieties that can
be repressed in a more public classroom setting. Another way to
achieve a safe learning environment is to have students discuss some
aspect of the problem with their peers in the classroom. This starts a
dialog that allows for peer learning, and it enables students to
express their thinking out loud. I ask students to discuss questions
in groups of two or three, and then I move between the groups to
facilitate discussions by asking students to explain their solution to
me, or by clarifying and guiding groups that struggle. Shuffling the
groups from time to time in invigorates discussion and seems to have a
positive impact on peer interactions.

I believe that all students can master the material when they are held
accountable, given adequate time, and are motivated. Accountability
means that the students' learning happens on their own account. I
engage in a question-answer dialogue, which leads the student through
the problem, allowing them to come to the solution on their own. I
also check students homework when they struggle, ensuring it is
completed and the solutions are communicated clearly. Finally, I
believe that the instructor should be as accountable as the student.
Therefore, when I make an error on the board that a student catches
and corrects, he or she receives a reward. In participating in
Teaching Triangles, a peer observation component of the Certificate in
College Teaching, I received two assessments from my peers. One peer
described my teaching style as one that "[[file:samps/david_d_observation_me.pdf][keeps the students engaged,
invested, and enthusiastic about physics.]]" In another observation, my
methods have been said to "[[file:samps/xuhui_b_observation_me.pdf][help {students} think independently and
critically.]]"

One of the most valuable products of each semester I've taught is the
student reviews. They provide an unvarnished assessment of my
teaching. I pay careful attention to the written comments and do my
best to incorporate changes to address them. One comment I received
during my first semester teaching a lab for "Introduction to
Mechanics" was that I erased the board too quickly. In subsequent
semesters I now ask if anyone needs the board before erasing. In my
most recent semester teaching recitation for "Introduction to Physics
for Engineers", students rated my confidence with the material lower
than I had hoped. On reflection, I think this was due to my
questioning the students if my choice of problems were too difficult.
In future semesters I will find different ways to assess how the
students are handling the material. I will solicit feedback midway to
address problems before finding out about them after the fact.

I have just begun my teaching career and the experiences I have had so
far have been formative. One of the best moments I had as a recitation
instructor was when one of my students finally understood how static
and kinetic friction are related to the normal force applied to an
object. This "A-Hah!" moment when a student makes the transition from
confusion to understanding is why I teach. In order to develop my
ability to facilitate this moment, I have completed the Certificate of
College Teaching program at Duke. I look forward to developing courses
in the future. Specifically, I would like to teach an upper level
undergraduate course on experimental methods in High Energy Physics, a
topic directly related to my research and rarely covered at the
undergraduate level. I also look forward to teaching introductory
level courses in physics and find myself thinking of ways to explain
difficult concepts to people who are hearing them for the first time.
I am constantly developing my teaching skills so that one day I will
have the same impact that my high school calculus teacher, and my
freshman physics teacher had on me.
